
/* A Bison parser, made by GNU Bison 2.4.1.  */

/* Skeleton implementation for Bison's Yacc-like parsers in C
   
      Copyright (C) 1984, 1989, 1990, 2000, 2001, 2002, 2003, 2004, 2005, 2006
   Free Software Foundation, Inc.
   
   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.
   
   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.
   
   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.
   
   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

/* C LALR(1) parser skeleton written by Richard Stallman, by
   simplifying the original so-called "semantic" parser.  */

/* All symbols defined below should begin with yy or YY, to avoid
   infringing on user name space.  This should be done even for local
   variables, as they might otherwise be expanded by user macros.
   There are some unavoidable exceptions within include files to
   define necessary library symbols; they are noted "INFRINGES ON
   USER NAME SPACE" below.  */

/* Identify Bison output.  */
#define YYBISON 1

/* Bison version.  */
#define YYBISON_VERSION "2.4.1"

/* Skeleton name.  */
#define YYSKELETON_NAME "yacc.c"

/* Pure parsers.  */
#define YYPURE 0

/* Push parsers.  */
#define YYPUSH 0

/* Pull parsers.  */
#define YYPULL 1

/* Using locations.  */
#define YYLSP_NEEDED 0



/* Copy the first part of user declarations.  */

/* Line 189 of yacc.c  */
#line 4 "parser.y"

	#include <cmath>
	#include <cstdio>
	#include <iostream>
	#include <string>

	extern int yylex(); //will be generated by flex
	extern void yyerror(const char*); //code this

	using namespace std;


/* Line 189 of yacc.c  */
#line 86 "parser.cpp"

/* Enabling traces.  */
#ifndef YYDEBUG
# define YYDEBUG 0
#endif

/* Enabling verbose error messages.  */
#ifdef YYERROR_VERBOSE
# undef YYERROR_VERBOSE
# define YYERROR_VERBOSE 1
#else
# define YYERROR_VERBOSE 0
#endif

/* Enabling the token table.  */
#ifndef YYTOKEN_TABLE
# define YYTOKEN_TABLE 0
#endif


/* Tokens.  */
#ifndef YYTOKENTYPE
# define YYTOKENTYPE
   /* Put the tokens into the symbol table, so that GDB and other debuggers
      know about them.  */
   enum yytokentype {
     INTEGER = 258,
     DECIMAL = 259,
     STRING = 260,
     BOOLEAN = 261,
     KW_AND = 262,
     KW_BOOLEAN = 263,
     KW_BREAK = 264,
     KW_CHOICE = 265,
     KW_CLASS = 266,
     KW_DOUBLE = 267,
     KW_FOR = 268,
     KW_FUNCTION = 269,
     KW_IF = 270,
     KW_IMPORT = 271,
     KW_INPUT = 272,
     KW_INT = 273,
     KW_LOOP = 274,
     KW_NEW = 275,
     KW_NOT = 276,
     KW_NULL = 277,
     KW_OR = 278,
     KW_OTHERWISE = 279,
     KW_PROMPT = 280,
     KW_RETURN = 281,
     KW_STRING = 282,
     KW_THIS = 283,
     KW_TO = 284,
     KW_UNLESS = 285,
     KW_UNTIL = 286,
     KW_WRITE = 287,
     KW_WRITELINE = 288,
     ADD = 289,
     SUB = 290,
     MUL = 291,
     DIV = 292,
     MOD = 293,
     EXP = 294,
     EQUALS = 295,
     ADD_EQ = 296,
     SUB_EQ = 297,
     MUL_EQ = 298,
     DIV_EQ = 299,
     MOD_EQ = 300,
     EXP_EQ = 301,
     INCREMENT = 302,
     DECREMENT = 303,
     IS_EQ_TO = 304,
     LESSTHAN = 305,
     GREATERTHAN = 306,
     LTorEQ = 307,
     GTorEQ = 308,
     NOT_EQ = 309,
     IDENTIFIER = 310,
     OPEN_PAREN = 311,
     CLOSE_PAREN = 312,
     OPEN_BRACE = 313,
     CLOSE_BRACE = 314,
     OPEN_BRACKET = 315,
     CLOSE_BRACKET = 316,
     MEMBER = 317,
     SEPARATOR = 318,
     END_STMT = 319,
     COMMENT = 320
   };
#endif



#if ! defined YYSTYPE && ! defined YYSTYPE_IS_DECLARED
typedef union YYSTYPE
{

/* Line 214 of yacc.c  */
#line 16 "parser.y"

	int intVal;
	double dblVal;
	char *strVal;
	bool boolVal;



/* Line 214 of yacc.c  */
#line 196 "parser.cpp"
} YYSTYPE;
# define YYSTYPE_IS_TRIVIAL 1
# define yystype YYSTYPE /* obsolescent; will be withdrawn */
# define YYSTYPE_IS_DECLARED 1
#endif


/* Copy the second part of user declarations.  */


/* Line 264 of yacc.c  */
#line 208 "parser.cpp"

#ifdef short
# undef short
#endif

#ifdef YYTYPE_UINT8
typedef YYTYPE_UINT8 yytype_uint8;
#else
typedef unsigned char yytype_uint8;
#endif

#ifdef YYTYPE_INT8
typedef YYTYPE_INT8 yytype_int8;
#elif (defined __STDC__ || defined __C99__FUNC__ \
     || defined __cplusplus || defined _MSC_VER)
typedef signed char yytype_int8;
#else
typedef short int yytype_int8;
#endif

#ifdef YYTYPE_UINT16
typedef YYTYPE_UINT16 yytype_uint16;
#else
typedef unsigned short int yytype_uint16;
#endif

#ifdef YYTYPE_INT16
typedef YYTYPE_INT16 yytype_int16;
#else
typedef short int yytype_int16;
#endif

#ifndef YYSIZE_T
# ifdef __SIZE_TYPE__
#  define YYSIZE_T __SIZE_TYPE__
# elif defined size_t
#  define YYSIZE_T size_t
# elif ! defined YYSIZE_T && (defined __STDC__ || defined __C99__FUNC__ \
     || defined __cplusplus || defined _MSC_VER)
#  include <stddef.h> /* INFRINGES ON USER NAME SPACE */
#  define YYSIZE_T size_t
# else
#  define YYSIZE_T unsigned int
# endif
#endif

#define YYSIZE_MAXIMUM ((YYSIZE_T) -1)

#ifndef YY_
# if YYENABLE_NLS
#  if ENABLE_NLS
#   include <libintl.h> /* INFRINGES ON USER NAME SPACE */
#   define YY_(msgid) dgettext ("bison-runtime", msgid)
#  endif
# endif
# ifndef YY_
#  define YY_(msgid) msgid
# endif
#endif

/* Suppress unused-variable warnings by "using" E.  */
#if ! defined lint || defined __GNUC__
# define YYUSE(e) ((void) (e))
#else
# define YYUSE(e) /* empty */
#endif

/* Identity function, used to suppress warnings about constant conditions.  */
#ifndef lint
# define YYID(n) (n)
#else
#if (defined __STDC__ || defined __C99__FUNC__ \
     || defined __cplusplus || defined _MSC_VER)
static int
YYID (int yyi)
#else
static int
YYID (yyi)
    int yyi;
#endif
{
  return yyi;
}
#endif

#if ! defined yyoverflow || YYERROR_VERBOSE

/* The parser invokes alloca or malloc; define the necessary symbols.  */

# ifdef YYSTACK_USE_ALLOCA
#  if YYSTACK_USE_ALLOCA
#   ifdef __GNUC__
#    define YYSTACK_ALLOC __builtin_alloca
#   elif defined __BUILTIN_VA_ARG_INCR
#    include <alloca.h> /* INFRINGES ON USER NAME SPACE */
#   elif defined _AIX
#    define YYSTACK_ALLOC __alloca
#   elif defined _MSC_VER
#    include <malloc.h> /* INFRINGES ON USER NAME SPACE */
#    define alloca _alloca
#   else
#    define YYSTACK_ALLOC alloca
#    if ! defined _ALLOCA_H && ! defined _STDLIB_H && (defined __STDC__ || defined __C99__FUNC__ \
     || defined __cplusplus || defined _MSC_VER)
#     include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
#     ifndef _STDLIB_H
#      define _STDLIB_H 1
#     endif
#    endif
#   endif
#  endif
# endif

# ifdef YYSTACK_ALLOC
   /* Pacify GCC's `empty if-body' warning.  */
#  define YYSTACK_FREE(Ptr) do { /* empty */; } while (YYID (0))
#  ifndef YYSTACK_ALLOC_MAXIMUM
    /* The OS might guarantee only one guard page at the bottom of the stack,
       and a page size can be as small as 4096 bytes.  So we cannot safely
       invoke alloca (N) if N exceeds 4096.  Use a slightly smaller number
       to allow for a few compiler-allocated temporary stack slots.  */
#   define YYSTACK_ALLOC_MAXIMUM 4032 /* reasonable circa 2006 */
#  endif
# else
#  define YYSTACK_ALLOC YYMALLOC
#  define YYSTACK_FREE YYFREE
#  ifndef YYSTACK_ALLOC_MAXIMUM
#   define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
#  endif
#  if (defined __cplusplus && ! defined _STDLIB_H \
       && ! ((defined YYMALLOC || defined malloc) \
	     && (defined YYFREE || defined free)))
#   include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
#   ifndef _STDLIB_H
#    define _STDLIB_H 1
#   endif
#  endif
#  ifndef YYMALLOC
#   define YYMALLOC malloc
#   if ! defined malloc && ! defined _STDLIB_H && (defined __STDC__ || defined __C99__FUNC__ \
     || defined __cplusplus || defined _MSC_VER)
void *malloc (YYSIZE_T); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
#  ifndef YYFREE
#   define YYFREE free
#   if ! defined free && ! defined _STDLIB_H && (defined __STDC__ || defined __C99__FUNC__ \
     || defined __cplusplus || defined _MSC_VER)
void free (void *); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
# endif
#endif /* ! defined yyoverflow || YYERROR_VERBOSE */


#if (! defined yyoverflow \
     && (! defined __cplusplus \
	 || (defined YYSTYPE_IS_TRIVIAL && YYSTYPE_IS_TRIVIAL)))

/* A type that is properly aligned for any stack member.  */
union yyalloc
{
  yytype_int16 yyss_alloc;
  YYSTYPE yyvs_alloc;
};

/* The size of the maximum gap between one aligned stack and the next.  */
# define YYSTACK_GAP_MAXIMUM (sizeof (union yyalloc) - 1)

/* The size of an array large to enough to hold all stacks, each with
   N elements.  */
# define YYSTACK_BYTES(N) \
     ((N) * (sizeof (yytype_int16) + sizeof (YYSTYPE)) \
      + YYSTACK_GAP_MAXIMUM)

/* Copy COUNT objects from FROM to TO.  The source and destination do
   not overlap.  */
# ifndef YYCOPY
#  if defined __GNUC__ && 1 < __GNUC__
#   define YYCOPY(To, From, Count) \
      __builtin_memcpy (To, From, (Count) * sizeof (*(From)))
#  else
#   define YYCOPY(To, From, Count)		\
      do					\
	{					\
	  YYSIZE_T yyi;				\
	  for (yyi = 0; yyi < (Count); yyi++)	\
	    (To)[yyi] = (From)[yyi];		\
	}					\
      while (YYID (0))
#  endif
# endif

/* Relocate STACK from its old location to the new one.  The
   local variables YYSIZE and YYSTACKSIZE give the old and new number of
   elements in the stack, and YYPTR gives the new location of the
   stack.  Advance YYPTR to a properly aligned location for the next
   stack.  */
# define YYSTACK_RELOCATE(Stack_alloc, Stack)				\
    do									\
      {									\
	YYSIZE_T yynewbytes;						\
	YYCOPY (&yyptr->Stack_alloc, Stack, yysize);			\
	Stack = &yyptr->Stack_alloc;					\
	yynewbytes = yystacksize * sizeof (*Stack) + YYSTACK_GAP_MAXIMUM; \
	yyptr += yynewbytes / sizeof (*yyptr);				\
      }									\
    while (YYID (0))

#endif

/* YYFINAL -- State number of the termination state.  */
#define YYFINAL  73
/* YYLAST -- Last index in YYTABLE.  */
#define YYLAST   772

/* YYNTOKENS -- Number of terminals.  */
#define YYNTOKENS  82
/* YYNNTS -- Number of nonterminals.  */
#define YYNNTS  45
/* YYNRULES -- Number of rules.  */
#define YYNRULES  131
/* YYNRULES -- Number of states.  */
#define YYNSTATES  294

/* YYTRANSLATE(YYLEX) -- Bison symbol number corresponding to YYLEX.  */
#define YYUNDEFTOK  2
#define YYMAXUTOK   320

#define YYTRANSLATE(YYX)						\
  ((unsigned int) (YYX) <= YYMAXUTOK ? yytranslate[YYX] : YYUNDEFTOK)

/* YYTRANSLATE[YYLEX] -- Bison symbol number corresponding to YYLEX.  */
static const yytype_uint8 yytranslate[] =
{
       0,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,    70,     2,     2,
      75,    76,    68,    66,    79,    67,    74,    69,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,    72,
       2,    73,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,    77,     2,    78,    71,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,    80,     2,    81,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     1,     2,     3,     4,
       5,     6,     7,     8,     9,    10,    11,    12,    13,    14,
      15,    16,    17,    18,    19,    20,    21,    22,    23,    24,
      25,    26,    27,    28,    29,    30,    31,    32,    33,    34,
      35,    36,    37,    38,    39,    40,    41,    42,    43,    44,
      45,    46,    47,    48,    49,    50,    51,    52,    53,    54,
      55,    56,    57,    58,    59,    60,    61,    62,    63,    64,
      65
};

#if YYDEBUG
/* YYPRHS[YYN] -- Index of the first RHS symbol of rule number YYN in
   YYRHS.  */
static const yytype_uint16 yyprhs[] =
{
       0,     0,     3,     5,     7,     8,    10,    13,    15,    17,
      19,    21,    23,    25,    27,    29,    31,    33,    35,    38,
      42,    47,    52,    57,    61,    66,    71,    78,    85,    88,
      90,    92,    94,    96,    98,   100,   102,   104,   108,   112,
     114,   118,   122,   126,   128,   132,   134,   136,   140,   144,
     146,   148,   150,   152,   154,   156,   158,   160,   162,   167,
     173,   180,   187,   188,   190,   192,   196,   200,   202,   204,
     206,   209,   217,   225,   230,   234,   238,   242,   248,   254,
     257,   259,   261,   263,   265,   267,   269,   278,   283,   289,
     295,   298,   305,   313,   320,   328,   330,   333,   335,   338,
     342,   344,   348,   350,   352,   354,   364,   381,   391,   401,
     407,   413,   415,   417,   419,   423,   427,   431,   438,   445,
     451,   453,   457,   461,   465,   471,   473,   475,   479,   481,
     483,   485
};

/* YYRHS -- A `-1'-separated list of the rules' RHS.  */
static const yytype_int8 yyrhs[] =
{
      83,     0,    -1,    84,    -1,    85,    -1,    -1,    86,    -1,
      85,    86,    -1,    87,    -1,    99,    -1,   101,    -1,   109,
      -1,   110,    -1,   111,    -1,   113,    -1,   115,    -1,   119,
      -1,   121,    -1,   124,    -1,    88,    72,    -1,    88,    97,
      72,    -1,    88,    73,    90,    72,    -1,    88,    73,    22,
      72,    -1,    88,    96,    90,    72,    -1,    55,    97,    72,
      -1,    55,    73,    90,    72,    -1,    55,    96,    90,    72,
      -1,    28,    74,    55,    73,   126,    72,    -1,    28,    74,
      55,    73,    55,    72,    -1,    89,    55,    -1,    18,    -1,
      12,    -1,    27,    -1,     8,    -1,    91,    -1,    95,    -1,
      98,    -1,    92,    -1,    91,    66,    92,    -1,    91,    67,
      92,    -1,    93,    -1,    92,    68,    93,    -1,    92,    69,
      93,    -1,    92,    70,    93,    -1,    94,    -1,    93,    71,
      94,    -1,     3,    -1,     4,    -1,    75,    91,    76,    -1,
      75,   105,    76,    -1,     6,    -1,    41,    -1,    42,    -1,
      43,    -1,    44,    -1,    45,    -1,    46,    -1,    47,    -1,
      48,    -1,    20,    55,    75,    76,    -1,    20,    55,    75,
     112,    76,    -1,    88,    73,    77,   100,    78,    72,    -1,
      55,    73,    77,   100,    78,    72,    -1,    -1,   126,    -1,
      55,    -1,   126,    79,   100,    -1,    55,    79,   100,    -1,
     102,    -1,   107,    -1,   103,    -1,   103,   104,    -1,    15,
      75,   105,    76,    77,    85,    78,    -1,    30,    75,   105,
      76,    77,    85,    78,    -1,    24,    77,    85,    78,    -1,
      90,   106,    90,    -1,   105,     7,   105,    -1,   105,    23,
     105,    -1,    90,   106,    90,     7,   105,    -1,    90,   106,
      90,    23,   105,    -1,    21,   105,    -1,    50,    -1,    51,
      -1,    49,    -1,    52,    -1,    53,    -1,    54,    -1,    10,
      75,    55,    76,    77,   108,    78,    72,    -1,   126,    80,
      85,    81,    -1,   108,   126,    80,    85,    81,    -1,   108,
      24,    80,    85,    81,    -1,     9,    72,    -1,    11,    75,
      76,    77,    85,    78,    -1,    11,    75,   112,    76,    77,
      85,    78,    -1,    14,    75,    76,    77,    85,    78,    -1,
      14,    75,   112,    76,    77,    85,    78,    -1,    88,    -1,
      88,   112,    -1,    55,    -1,    55,   112,    -1,    16,   114,
      72,    -1,    55,    -1,    55,    74,   114,    -1,   116,    -1,
     117,    -1,   118,    -1,    19,    77,    85,    78,    31,    75,
     105,    76,    72,    -1,    19,    77,    85,    78,    31,    75,
     105,    76,    30,    75,   105,    76,    77,    85,    78,    72,
      -1,    13,    75,    55,    29,     3,    76,    77,    85,    78,
      -1,    13,    75,    55,    29,     4,    76,    77,    85,    78,
      -1,    32,    75,   120,    76,    72,    -1,    33,    75,   120,
      76,    72,    -1,   126,    -1,    55,    -1,    90,    -1,   126,
      79,   120,    -1,    55,    79,   120,    -1,    90,    79,   120,
      -1,    25,    75,     5,    76,   122,    72,    -1,    25,    75,
      55,    76,   122,    72,    -1,    17,    77,   123,    78,    72,
      -1,    55,    -1,    55,    79,   123,    -1,    26,   126,    72,
      -1,    26,    55,    72,    -1,    26,    77,   125,    78,    72,
      -1,   126,    -1,    55,    -1,    77,    85,    78,    -1,     3,
      -1,     4,    -1,     5,    -1,     6,    -1
};

/* YYRLINE[YYN] -- source line where rule number YYN was defined.  */
static const yytype_uint16 yyrline[] =
{
       0,   104,   104,   107,   110,   111,   112,   115,   116,   117,
     118,   119,   120,   121,   122,   123,   124,   125,   128,   129,
     130,   131,   132,   133,   134,   135,   136,   137,   140,   143,
     144,   145,   146,   149,   150,   151,   154,   155,   156,   159,
     160,   161,   162,   165,   166,   169,   170,   171,   172,   175,
     178,   179,   180,   181,   182,   183,   186,   187,   190,   191,
     194,   195,   198,   199,   200,   201,   202,   205,   206,   209,
     210,   213,   216,   217,   220,   221,   222,   223,   224,   225,
     228,   229,   230,   231,   232,   233,   236,   239,   240,   241,
     244,   247,   248,   251,   252,   255,   256,   257,   258,   261,
     264,   265,   268,   271,   272,   275,   276,   279,   280,   283,
     284,   287,   288,   289,   290,   291,   292,   295,   296,   299,
     302,   303,   306,   307,   308,   311,   312,   313,   316,   317,
     318,   319
};
#endif

#if YYDEBUG || YYERROR_VERBOSE || YYTOKEN_TABLE
/* YYTNAME[SYMBOL-NUM] -- String name of the symbol SYMBOL-NUM.
   First, the terminals, then, starting at YYNTOKENS, nonterminals.  */
static const char *const yytname[] =
{
  "$end", "error", "$undefined", "INTEGER", "DECIMAL", "STRING",
  "BOOLEAN", "KW_AND", "KW_BOOLEAN", "KW_BREAK", "KW_CHOICE", "KW_CLASS",
  "KW_DOUBLE", "KW_FOR", "KW_FUNCTION", "KW_IF", "KW_IMPORT", "KW_INPUT",
  "KW_INT", "KW_LOOP", "KW_NEW", "KW_NOT", "KW_NULL", "KW_OR",
  "KW_OTHERWISE", "KW_PROMPT", "KW_RETURN", "KW_STRING", "KW_THIS",
  "KW_TO", "KW_UNLESS", "KW_UNTIL", "KW_WRITE", "KW_WRITELINE", "ADD",
  "SUB", "MUL", "DIV", "MOD", "EXP", "EQUALS", "ADD_EQ", "SUB_EQ",
  "MUL_EQ", "DIV_EQ", "MOD_EQ", "EXP_EQ", "INCREMENT", "DECREMENT",
  "IS_EQ_TO", "LESSTHAN", "GREATERTHAN", "LTorEQ", "GTorEQ", "NOT_EQ",
  "IDENTIFIER", "OPEN_PAREN", "CLOSE_PAREN", "OPEN_BRACE", "CLOSE_BRACE",
  "OPEN_BRACKET", "CLOSE_BRACKET", "MEMBER", "SEPARATOR", "END_STMT",
  "COMMENT", "'+'", "'-'", "'*'", "'/'", "'%'", "'^'", "';'", "'='", "'.'",
  "'('", "')'", "'['", "']'", "','", "'{'", "'}'", "$accept", "program",
  "file", "statements", "statement", "assignment", "var", "data_type",
  "expression", "add_sub", "mul_div", "expnt", "paren", "bool", "op_equal",
  "small_op", "obj_assign", "array", "arr_content", "branch", "if_stmt",
  "req_if_stmt", "opt_if_stmt", "conditions", "cond_op", "choice_stmt",
  "choice_expr", "break", "class", "function", "parameters", "import",
  "package", "loop", "loop_type", "default", "forloop", "print",
  "write_expr", "prompt", "input", "input_list", "return_stmt",
  "return_list", "literal", 0
};
#endif

# ifdef YYPRINT
/* YYTOKNUM[YYLEX-NUM] -- Internal token number corresponding to
   token YYLEX-NUM.  */
static const yytype_uint16 yytoknum[] =
{
       0,   256,   257,   258,   259,   260,   261,   262,   263,   264,
     265,   266,   267,   268,   269,   270,   271,   272,   273,   274,
     275,   276,   277,   278,   279,   280,   281,   282,   283,   284,
     285,   286,   287,   288,   289,   290,   291,   292,   293,   294,
     295,   296,   297,   298,   299,   300,   301,   302,   303,   304,
     305,   306,   307,   308,   309,   310,   311,   312,   313,   314,
     315,   316,   317,   318,   319,   320,    43,    45,    42,    47,
      37,    94,    59,    61,    46,    40,    41,    91,    93,    44,
     123,   125
};
# endif

/* YYR1[YYN] -- Symbol number of symbol that rule YYN derives.  */
static const yytype_uint8 yyr1[] =
{
       0,    82,    83,    84,    85,    85,    85,    86,    86,    86,
      86,    86,    86,    86,    86,    86,    86,    86,    87,    87,
      87,    87,    87,    87,    87,    87,    87,    87,    88,    89,
      89,    89,    89,    90,    90,    90,    91,    91,    91,    92,
      92,    92,    92,    93,    93,    94,    94,    94,    94,    95,
      96,    96,    96,    96,    96,    96,    97,    97,    98,    98,
      99,    99,   100,   100,   100,   100,   100,   101,   101,   102,
     102,   103,   104,   104,   105,   105,   105,   105,   105,   105,
     106,   106,   106,   106,   106,   106,   107,   108,   108,   108,
     109,   110,   110,   111,   111,   112,   112,   112,   112,   113,
     114,   114,   115,   116,   116,   117,   117,   118,   118,   119,
     119,   120,   120,   120,   120,   120,   120,   121,   121,   122,
     123,   123,   124,   124,   124,   125,   125,   125,   126,   126,
     126,   126
};

/* YYR2[YYN] -- Number of symbols composing right hand side of rule YYN.  */
static const yytype_uint8 yyr2[] =
{
       0,     2,     1,     1,     0,     1,     2,     1,     1,     1,
       1,     1,     1,     1,     1,     1,     1,     1,     2,     3,
       4,     4,     4,     3,     4,     4,     6,     6,     2,     1,
       1,     1,     1,     1,     1,     1,     1,     3,     3,     1,
       3,     3,     3,     1,     3,     1,     1,     3,     3,     1,
       1,     1,     1,     1,     1,     1,     1,     1,     4,     5,
       6,     6,     0,     1,     1,     3,     3,     1,     1,     1,
       2,     7,     7,     4,     3,     3,     3,     5,     5,     2,
       1,     1,     1,     1,     1,     1,     8,     4,     5,     5,
       2,     6,     7,     6,     7,     1,     2,     1,     2,     3,
       1,     3,     1,     1,     1,     9,    16,     9,     9,     5,
       5,     1,     1,     1,     3,     3,     3,     6,     6,     5,
       1,     3,     3,     3,     5,     1,     1,     3,     1,     1,
       1,     1
};

/* YYDEFACT[STATE-NAME] -- Default rule to reduce with in state
   STATE-NUM when YYTABLE doesn't specify something else to do.  Zero
   means the default is an error.  */
static const yytype_uint8 yydefact[] =
{
       4,    32,     0,     0,     0,    30,     0,     0,     0,     0,
      29,     0,     0,     0,    31,     0,     0,     0,     0,     0,
       2,     3,     5,     7,     0,     0,     8,     9,    67,    69,
      68,    10,    11,    12,    13,    14,   102,   103,   104,    15,
      16,    17,    90,     0,     0,     0,     0,     0,   100,     0,
       4,     0,   128,   129,   130,   131,     0,     0,     0,     0,
       0,     0,    50,    51,    52,    53,    54,    55,    56,    57,
       0,     0,     0,     1,     6,    18,     0,     0,     0,    28,
       0,     0,    70,     0,    97,     0,    95,     0,     0,     0,
       0,    45,    46,    49,     0,     0,     0,     0,    33,    36,
      39,    43,    34,    35,     0,     0,    99,     0,     0,     0,
     123,   126,     4,     0,   125,   122,     0,    45,    46,    49,
     112,   113,     0,   111,     0,    62,     0,     0,    23,     0,
      62,     0,     0,    19,     4,     0,     0,    98,     4,    96,
       0,     0,     4,     0,     0,    79,    33,     0,    82,    80,
      81,    83,    84,    85,     0,     0,     0,     0,     0,     0,
       0,     0,     0,     0,   101,     0,     0,     0,     0,     0,
       0,     0,     0,     0,     0,     0,    64,     0,    63,    24,
      25,    21,     0,    20,    22,     0,     0,     0,     0,     4,
       0,     0,     0,     4,     0,    47,    48,    74,    37,    38,
      40,    41,    42,    44,    75,    76,     4,     0,     0,     0,
       0,   127,   124,     0,     0,   115,   116,   109,   114,   110,
      62,     0,    62,     0,    73,     0,     0,     0,    91,     0,
       0,     0,    93,     0,    58,     0,     0,     0,     0,     0,
       0,   117,   118,    27,    26,    66,    61,    65,    60,     4,
       0,     0,     0,     4,    92,     4,     4,    94,    59,    77,
      78,    71,     0,   120,     0,     0,     4,    86,     4,     0,
       0,     0,     0,     0,     0,    72,     0,     0,    87,   107,
     108,     0,   105,   121,   119,    89,    88,     0,     0,     0,
       4,     0,     0,   106
};

/* YYDEFGOTO[NTERM-NUM].  */
static const yytype_int16 yydefgoto[] =
{
      -1,    19,    20,    21,    22,    23,    24,    25,    97,    98,
      99,   100,   101,   102,    71,    72,   103,    26,   177,    27,
      28,    29,    82,   104,   154,    30,   226,    31,    32,    33,
      87,    34,    49,    35,    36,    37,    38,    39,   122,    40,
     209,   264,    41,   113,   123
};

/* YYPACT[STATE-NUM] -- Index in YYTABLE of the portion describing
   STATE-NUM.  */
#define YYPACT_NINF -125
static const yytype_int16 yypact[] =
{
     706,  -125,   -64,   -44,   -42,  -125,   -23,     1,    16,   -13,
    -125,   -66,    29,    18,  -125,    19,    31,    37,   653,   116,
    -125,   706,  -125,  -125,   699,    75,  -125,  -125,  -125,    70,
    -125,  -125,  -125,  -125,  -125,  -125,  -125,  -125,  -125,  -125,
    -125,  -125,  -125,    79,    99,    84,   637,    47,    83,    60,
     706,    35,  -125,  -125,  -125,  -125,    72,    33,    81,   103,
      58,    58,  -125,  -125,  -125,  -125,  -125,  -125,  -125,  -125,
      54,    77,    93,  -125,  -125,  -125,    12,    77,    94,  -125,
      97,   114,  -125,   117,   224,   118,   224,   125,   165,   126,
     130,  -125,  -125,  -125,   147,    47,    47,   266,   -12,   100,
     136,  -125,  -125,  -125,    42,   -13,  -125,   314,   134,   138,
    -125,  -125,   706,   135,  -125,  -125,   145,  -125,  -125,  -125,
     140,   142,   148,   146,   150,   137,   162,   169,  -125,   171,
     137,   173,   174,  -125,   706,    47,   170,  -125,   706,  -125,
     175,   133,   706,   177,   192,    49,    96,    52,  -125,  -125,
    -125,  -125,  -125,  -125,    77,     9,     9,     9,     9,     9,
       9,    47,    47,   194,  -125,   241,   256,   256,   340,   202,
     225,    58,    58,   209,    58,   212,   206,   208,   219,  -125,
    -125,  -125,   210,  -125,  -125,   371,    59,   234,   397,   706,
     211,   226,   428,   706,   651,  -125,  -125,    92,   100,   100,
     136,   136,   136,  -125,    49,    49,   706,   228,   227,   229,
     238,  -125,  -125,   239,   240,  -125,  -125,  -125,  -125,  -125,
     137,   249,   137,   262,  -125,   258,    24,   257,  -125,   454,
     261,   267,  -125,   485,  -125,   269,    47,    47,   511,    47,
     288,  -125,  -125,  -125,  -125,  -125,  -125,  -125,  -125,   706,
     277,   289,   280,   706,  -125,   706,   706,  -125,  -125,    49,
      49,  -125,    62,   284,   286,   542,   706,  -125,   706,   172,
     568,   599,     5,   288,   298,  -125,   250,   281,  -125,  -125,
    -125,   296,  -125,  -125,  -125,  -125,  -125,    47,    85,   297,
     706,   625,   303,  -125
};

/* YYPGOTO[NTERM-NUM].  */
static const yytype_int16 yypgoto[] =
{
    -125,  -125,  -125,   -33,   -21,  -125,   -43,  -125,   -51,   282,
      -6,    20,   216,  -125,   353,   364,  -125,  -125,  -124,  -125,
    -125,  -125,  -125,   -91,  -125,  -125,  -125,  -125,  -125,  -125,
     -39,  -125,   295,  -125,  -125,  -125,  -125,  -125,   -47,  -125,
     235,   120,  -125,  -125,   -11
};

/* YYTABLE[YYPACT[STATE-NUM]].  What to do in state STATE-NUM.  If
   positive, shift that token.  If negative, reduce the rule which
   number is the opposite.  If zero, do what YYDEFACT says.
   If YYTABLE_NINF, syntax error.  */
#define YYTABLE_NINF -1
static const yytype_uint16 yytable[] =
{
      74,    86,    58,    86,   145,   147,   182,    90,    42,   121,
     121,    50,    91,    92,   124,    91,    92,   107,    93,   126,
     127,    52,    53,    54,    55,   131,   132,    52,    53,    54,
      55,    43,    94,    44,   129,   281,    52,    53,    54,    55,
     108,    86,    48,    86,   186,   137,   114,   139,   250,   161,
      91,    92,    45,    93,   155,   156,   161,    91,    92,   161,
      93,   117,   118,    54,   119,   162,   161,    94,    95,   161,
     204,   205,   162,    56,    94,   162,    46,   282,    94,   168,
      91,    92,   162,    93,    96,   162,    74,    96,   111,   130,
     109,    47,   161,    59,    80,    57,   245,    94,   247,   236,
      81,   185,   251,   197,    51,   188,    60,     1,   162,   192,
     112,     5,    61,   120,   178,   237,    73,    10,   163,   178,
     121,   121,    96,   121,   215,   216,    14,   218,   196,    96,
      79,   125,   106,    96,    83,   225,   190,   191,   272,    88,
      52,    53,    54,    55,   110,   259,   260,    74,   262,   198,
     199,    86,    96,   115,    84,   235,   229,   105,   116,   214,
     233,   289,   155,   156,    74,   128,   133,    74,   157,   158,
     159,    74,   195,   238,   134,    85,   227,   200,   201,   202,
       1,     2,     3,     4,     5,     6,     7,     8,     9,   135,
      10,    11,   176,   136,   141,   138,   288,    12,    13,    14,
      15,   140,   144,   142,    16,    17,   143,   160,    74,   178,
     166,   178,    74,   169,   167,   252,   265,    74,   170,   171,
     269,   172,   270,   271,   173,   174,   175,    18,    52,    53,
      54,    55,     1,   276,   179,   277,     5,    52,    53,    54,
      55,   180,    10,   181,    74,   183,   184,   187,    74,    74,
      74,    14,   189,   278,   193,    74,    74,   291,     1,     2,
       3,     4,     5,     6,     7,     8,     9,   194,    10,    11,
      74,   206,   207,   208,   212,    12,    13,    14,    15,    84,
     213,   217,    16,    17,   219,   220,   221,   230,   223,     1,
       2,     3,     4,     5,     6,     7,     8,     9,   222,    10,
      11,   241,   231,   239,   240,    18,    12,    13,    14,    15,
     242,   243,   244,    16,    17,   148,   149,   150,   151,   152,
     153,   246,     1,     2,     3,     4,     5,     6,     7,     8,
       9,   285,    10,    11,   248,   249,    18,   253,   255,    12,
      13,    14,    15,   263,   256,   258,    16,    17,     1,     2,
       3,     4,     5,     6,     7,     8,     9,   266,    10,    11,
     268,   267,   286,   273,   274,    12,    13,    14,    15,    18,
     284,   287,    16,    17,   290,   293,   203,    77,   146,     1,
       2,     3,     4,     5,     6,     7,     8,     9,    78,    10,
      11,     0,   165,   283,     0,    18,    12,    13,    14,    15,
     164,     0,   210,    16,    17,     1,     2,     3,     4,     5,
       6,     7,     8,     9,     0,    10,    11,     0,   211,     0,
       0,     0,    12,    13,    14,    15,    18,     0,     0,    16,
      17,     0,     0,     0,     0,     0,     1,     2,     3,     4,
       5,     6,     7,     8,     9,     0,    10,    11,     0,   224,
       0,     0,    18,    12,    13,    14,    15,     0,     0,     0,
      16,    17,     1,     2,     3,     4,     5,     6,     7,     8,
       9,     0,    10,    11,     0,   228,     0,     0,     0,    12,
      13,    14,    15,    18,     0,     0,    16,    17,     0,     0,
       0,     0,     0,     1,     2,     3,     4,     5,     6,     7,
       8,     9,     0,    10,    11,     0,   232,     0,     0,    18,
      12,    13,    14,    15,     0,     0,     0,    16,    17,     1,
       2,     3,     4,     5,     6,     7,     8,     9,     0,    10,
      11,     0,   254,     0,     0,     0,    12,    13,    14,    15,
      18,     0,     0,    16,    17,     0,     0,     0,     0,     0,
       1,     2,     3,     4,     5,     6,     7,     8,     9,     0,
      10,    11,     0,   257,     0,     0,    18,    12,    13,    14,
      15,     0,     0,     0,    16,    17,     1,     2,     3,     4,
       5,     6,     7,     8,     9,     0,    10,    11,     0,   261,
       0,     0,     0,    12,    13,    14,    15,    18,     0,     0,
      16,    17,     0,     0,     0,     0,     0,     1,     2,     3,
       4,     5,     6,     7,     8,     9,     0,    10,    11,     0,
     275,     0,     0,    18,    12,    13,    14,    15,     0,     0,
       0,    16,    17,     1,     2,     3,     4,     5,     6,     7,
       8,     9,     0,    10,    11,     1,   279,     0,     0,     5,
      12,    13,    14,    15,    18,    10,     0,    16,    17,     1,
       0,     0,     0,     5,    14,     0,     0,     0,     0,    10,
       0,     0,     0,     0,     0,     0,     0,   280,    14,     0,
      18,     0,     0,     0,     0,     0,     0,     0,     0,     0,
       0,     0,    84,     0,    62,    63,    64,    65,    66,    67,
      68,    69,     0,   292,     0,     0,    84,     0,     0,     0,
       0,     0,     0,    89,     1,     2,     3,     4,     5,     6,
       7,     8,     9,     0,    10,    11,    70,   234,     0,     0,
       0,    12,    13,    14,    15,     0,     0,     0,    16,    17,
      62,    63,    64,    65,    66,    67,    68,    69,     0,     0,
       0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
       0,    18,     0,     0,     0,     0,     0,     0,     0,     0,
       0,    75,    76
};

static const yytype_int16 yycheck[] =
{
      21,    44,    13,    46,    95,    96,   130,    46,    72,    60,
      61,    77,     3,     4,    61,     3,     4,    50,     6,    70,
      71,     3,     4,     5,     6,    76,    77,     3,     4,     5,
       6,    75,    20,    75,    22,    30,     3,     4,     5,     6,
       5,    84,    55,    86,   135,    84,    57,    86,    24,     7,
       3,     4,    75,     6,    66,    67,     7,     3,     4,     7,
       6,     3,     4,     5,     6,    23,     7,    20,    21,     7,
     161,   162,    23,    55,    20,    23,    75,    72,    20,   112,
       3,     4,    23,     6,    75,    23,   107,    75,    55,    77,
      55,    75,     7,    74,    24,    77,   220,    20,   222,     7,
      30,   134,    78,   154,    75,   138,    75,     8,    23,   142,
      77,    12,    75,    55,   125,    23,     0,    18,    76,   130,
     171,   172,    75,   174,   171,   172,    27,   174,    76,    75,
      55,    77,    72,    75,    55,    76,     3,     4,    76,    55,
       3,     4,     5,     6,    72,   236,   237,   168,   239,   155,
     156,   194,    75,    72,    55,   194,   189,    74,    55,   170,
     193,    76,    66,    67,   185,    72,    72,   188,    68,    69,
      70,   192,    76,   206,    77,    76,   187,   157,   158,   159,
       8,     9,    10,    11,    12,    13,    14,    15,    16,    75,
      18,    19,    55,    76,    29,    77,   287,    25,    26,    27,
      28,    76,    55,    77,    32,    33,    76,    71,   229,   220,
      76,   222,   233,    78,    76,   226,   249,   238,    73,    79,
     253,    79,   255,   256,    76,    79,    76,    55,     3,     4,
       5,     6,     8,   266,    72,   268,    12,     3,     4,     5,
       6,    72,    18,    72,   265,    72,    72,    77,   269,   270,
     271,    27,    77,    81,    77,   276,   277,   290,     8,     9,
      10,    11,    12,    13,    14,    15,    16,    75,    18,    19,
     291,    77,    31,    17,    72,    25,    26,    27,    28,    55,
      55,    72,    32,    33,    72,    79,    78,    76,    78,     8,
       9,    10,    11,    12,    13,    14,    15,    16,    79,    18,
      19,    72,    76,    75,    77,    55,    25,    26,    27,    28,
      72,    72,    72,    32,    33,    49,    50,    51,    52,    53,
      54,    72,     8,     9,    10,    11,    12,    13,    14,    15,
      16,    81,    18,    19,    72,    77,    55,    80,    77,    25,
      26,    27,    28,    55,    77,    76,    32,    33,     8,     9,
      10,    11,    12,    13,    14,    15,    16,    80,    18,    19,
      80,    72,    81,    79,    78,    25,    26,    27,    28,    55,
      72,    75,    32,    33,    77,    72,   160,    24,    96,     8,
       9,    10,    11,    12,    13,    14,    15,    16,    24,    18,
      19,    -1,    78,   273,    -1,    55,    25,    26,    27,    28,
     105,    -1,   167,    32,    33,     8,     9,    10,    11,    12,
      13,    14,    15,    16,    -1,    18,    19,    -1,    78,    -1,
      -1,    -1,    25,    26,    27,    28,    55,    -1,    -1,    32,
      33,    -1,    -1,    -1,    -1,    -1,     8,     9,    10,    11,
      12,    13,    14,    15,    16,    -1,    18,    19,    -1,    78,
      -1,    -1,    55,    25,    26,    27,    28,    -1,    -1,    -1,
      32,    33,     8,     9,    10,    11,    12,    13,    14,    15,
      16,    -1,    18,    19,    -1,    78,    -1,    -1,    -1,    25,
      26,    27,    28,    55,    -1,    -1,    32,    33,    -1,    -1,
      -1,    -1,    -1,     8,     9,    10,    11,    12,    13,    14,
      15,    16,    -1,    18,    19,    -1,    78,    -1,    -1,    55,
      25,    26,    27,    28,    -1,    -1,    -1,    32,    33,     8,
       9,    10,    11,    12,    13,    14,    15,    16,    -1,    18,
      19,    -1,    78,    -1,    -1,    -1,    25,    26,    27,    28,
      55,    -1,    -1,    32,    33,    -1,    -1,    -1,    -1,    -1,
       8,     9,    10,    11,    12,    13,    14,    15,    16,    -1,
      18,    19,    -1,    78,    -1,    -1,    55,    25,    26,    27,
      28,    -1,    -1,    -1,    32,    33,     8,     9,    10,    11,
      12,    13,    14,    15,    16,    -1,    18,    19,    -1,    78,
      -1,    -1,    -1,    25,    26,    27,    28,    55,    -1,    -1,
      32,    33,    -1,    -1,    -1,    -1,    -1,     8,     9,    10,
      11,    12,    13,    14,    15,    16,    -1,    18,    19,    -1,
      78,    -1,    -1,    55,    25,    26,    27,    28,    -1,    -1,
      -1,    32,    33,     8,     9,    10,    11,    12,    13,    14,
      15,    16,    -1,    18,    19,     8,    78,    -1,    -1,    12,
      25,    26,    27,    28,    55,    18,    -1,    32,    33,     8,
      -1,    -1,    -1,    12,    27,    -1,    -1,    -1,    -1,    18,
      -1,    -1,    -1,    -1,    -1,    -1,    -1,    78,    27,    -1,
      55,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
      -1,    -1,    55,    -1,    41,    42,    43,    44,    45,    46,
      47,    48,    -1,    78,    -1,    -1,    55,    -1,    -1,    -1,
      -1,    -1,    -1,    76,     8,     9,    10,    11,    12,    13,
      14,    15,    16,    -1,    18,    19,    73,    76,    -1,    -1,
      -1,    25,    26,    27,    28,    -1,    -1,    -1,    32,    33,
      41,    42,    43,    44,    45,    46,    47,    48,    -1,    -1,
      -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
      -1,    55,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
      -1,    72,    73
};

/* YYSTOS[STATE-NUM] -- The (internal number of the) accessing
   symbol of state STATE-NUM.  */
static const yytype_uint8 yystos[] =
{
       0,     8,     9,    10,    11,    12,    13,    14,    15,    16,
      18,    19,    25,    26,    27,    28,    32,    33,    55,    83,
      84,    85,    86,    87,    88,    89,    99,   101,   102,   103,
     107,   109,   110,   111,   113,   115,   116,   117,   118,   119,
     121,   124,    72,    75,    75,    75,    75,    75,    55,   114,
      77,    75,     3,     4,     5,     6,    55,    77,   126,    74,
      75,    75,    41,    42,    43,    44,    45,    46,    47,    48,
      73,    96,    97,     0,    86,    72,    73,    96,    97,    55,
      24,    30,   104,    55,    55,    76,    88,   112,    55,    76,
     112,     3,     4,     6,    20,    21,    75,    90,    91,    92,
      93,    94,    95,    98,   105,    74,    72,    85,     5,    55,
      72,    55,    77,   125,   126,    72,    55,     3,     4,     6,
      55,    90,   120,   126,   120,    77,    90,    90,    72,    22,
      77,    90,    90,    72,    77,    75,    76,   112,    77,   112,
      76,    29,    77,    76,    55,   105,    91,   105,    49,    50,
      51,    52,    53,    54,   106,    66,    67,    68,    69,    70,
      71,     7,    23,    76,   114,    78,    76,    76,    85,    78,
      73,    79,    79,    76,    79,    76,    55,   100,   126,    72,
      72,    72,   100,    72,    72,    85,   105,    77,    85,    77,
       3,     4,    85,    77,    75,    76,    76,    90,    92,    92,
      93,    93,    93,    94,   105,   105,    77,    31,    17,   122,
     122,    78,    72,    55,   126,   120,   120,    72,   120,    72,
      79,    78,    79,    78,    78,    76,   108,   126,    78,    85,
      76,    76,    78,    85,    76,   112,     7,    23,    85,    75,
      77,    72,    72,    72,    72,   100,    72,   100,    72,    77,
      24,    78,   126,    80,    78,    77,    77,    78,    76,   105,
     105,    78,   105,    55,   123,    85,    80,    72,    80,    85,
      85,    85,    76,    79,    78,    78,    85,    85,    81,    78,
      78,    30,    72,   123,    72,    81,    81,    75,   105,    76,
      77,    85,    78,    72
};

#define yyerrok		(yyerrstatus = 0)
#define yyclearin	(yychar = YYEMPTY)
#define YYEMPTY		(-2)
#define YYEOF		0

#define YYACCEPT	goto yyacceptlab
#define YYABORT		goto yyabortlab
#define YYERROR		goto yyerrorlab


/* Like YYERROR except do call yyerror.  This remains here temporarily
   to ease the transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */

#define YYFAIL		goto yyerrlab

#define YYRECOVERING()  (!!yyerrstatus)

#define YYBACKUP(Token, Value)					\
do								\
  if (yychar == YYEMPTY && yylen == 1)				\
    {								\
      yychar = (Token);						\
      yylval = (Value);						\
      yytoken = YYTRANSLATE (yychar);				\
      YYPOPSTACK (1);						\
      goto yybackup;						\
    }								\
  else								\
    {								\
      yyerror (YY_("syntax error: cannot back up")); \
      YYERROR;							\
    }								\
while (YYID (0))


#define YYTERROR	1
#define YYERRCODE	256


/* YYLLOC_DEFAULT -- Set CURRENT to span from RHS[1] to RHS[N].
   If N is 0, then set CURRENT to the empty location which ends
   the previous symbol: RHS[0] (always defined).  */

#define YYRHSLOC(Rhs, K) ((Rhs)[K])
#ifndef YYLLOC_DEFAULT
# define YYLLOC_DEFAULT(Current, Rhs, N)				\
    do									\
      if (YYID (N))                                                    \
	{								\
	  (Current).first_line   = YYRHSLOC (Rhs, 1).first_line;	\
	  (Current).first_column = YYRHSLOC (Rhs, 1).first_column;	\
	  (Current).last_line    = YYRHSLOC (Rhs, N).last_line;		\
	  (Current).last_column  = YYRHSLOC (Rhs, N).last_column;	\
	}								\
      else								\
	{								\
	  (Current).first_line   = (Current).last_line   =		\
	    YYRHSLOC (Rhs, 0).last_line;				\
	  (Current).first_column = (Current).last_column =		\
	    YYRHSLOC (Rhs, 0).last_column;				\
	}								\
    while (YYID (0))
#endif


/* YY_LOCATION_PRINT -- Print the location on the stream.
   This macro was not mandated originally: define only if we know
   we won't break user code: when these are the locations we know.  */

#ifndef YY_LOCATION_PRINT
# if YYLTYPE_IS_TRIVIAL
#  define YY_LOCATION_PRINT(File, Loc)			\
     fprintf (File, "%d.%d-%d.%d",			\
	      (Loc).first_line, (Loc).first_column,	\
	      (Loc).last_line,  (Loc).last_column)
# else
#  define YY_LOCATION_PRINT(File, Loc) ((void) 0)
# endif
#endif


/* YYLEX -- calling `yylex' with the right arguments.  */

#ifdef YYLEX_PARAM
# define YYLEX yylex (YYLEX_PARAM)
#else
# define YYLEX yylex ()
#endif

/* Enable debugging if requested.  */
#if YYDEBUG

# ifndef YYFPRINTF
#  include <stdio.h> /* INFRINGES ON USER NAME SPACE */
#  define YYFPRINTF fprintf
# endif

# define YYDPRINTF(Args)			\
do {						\
  if (yydebug)					\
    YYFPRINTF Args;				\
} while (YYID (0))

# define YY_SYMBOL_PRINT(Title, Type, Value, Location)			  \
do {									  \
  if (yydebug)								  \
    {									  \
      YYFPRINTF (stderr, "%s ", Title);					  \
      yy_symbol_print (stderr,						  \
		  Type, Value); \
      YYFPRINTF (stderr, "\n");						  \
    }									  \
} while (YYID (0))


/*--------------------------------.
| Print this symbol on YYOUTPUT.  |
`--------------------------------*/

/*ARGSUSED*/
#if (defined __STDC__ || defined __C99__FUNC__ \
     || defined __cplusplus || defined _MSC_VER)
static void
yy_symbol_value_print (FILE *yyoutput, int yytype, YYSTYPE const * const yyvaluep)
#else
static void
yy_symbol_value_print (yyoutput, yytype, yyvaluep)
    FILE *yyoutput;
    int yytype;
    YYSTYPE const * const yyvaluep;
#endif
{
  if (!yyvaluep)
    return;
# ifdef YYPRINT
  if (yytype < YYNTOKENS)
    YYPRINT (yyoutput, yytoknum[yytype], *yyvaluep);
# else
  YYUSE (yyoutput);
# endif
  switch (yytype)
    {
      default:
	break;
    }
}


/*--------------------------------.
| Print this symbol on YYOUTPUT.  |
`--------------------------------*/

#if (defined __STDC__ || defined __C99__FUNC__ \
     || defined __cplusplus || defined _MSC_VER)
static void
yy_symbol_print (FILE *yyoutput, int yytype, YYSTYPE const * const yyvaluep)
#else
static void
yy_symbol_print (yyoutput, yytype, yyvaluep)
    FILE *yyoutput;
    int yytype;
    YYSTYPE const * const yyvaluep;
#endif
{
  if (yytype < YYNTOKENS)
    YYFPRINTF (yyoutput, "token %s (", yytname[yytype]);
  else
    YYFPRINTF (yyoutput, "nterm %s (", yytname[yytype]);

  yy_symbol_value_print (yyoutput, yytype, yyvaluep);
  YYFPRINTF (yyoutput, ")");
}

/*------------------------------------------------------------------.
| yy_stack_print -- Print the state stack from its BOTTOM up to its |
| TOP (included).                                                   |
`------------------------------------------------------------------*/

#if (defined __STDC__ || defined __C99__FUNC__ \
     || defined __cplusplus || defined _MSC_VER)
static void
yy_stack_print (yytype_int16 *yybottom, yytype_int16 *yytop)
#else
static void
yy_stack_print (yybottom, yytop)
    yytype_int16 *yybottom;
    yytype_int16 *yytop;
#endif
{
  YYFPRINTF (stderr, "Stack now");
  for (; yybottom <= yytop; yybottom++)
    {
      int yybot = *yybottom;
      YYFPRINTF (stderr, " %d", yybot);
    }
  YYFPRINTF (stderr, "\n");
}

# define YY_STACK_PRINT(Bottom, Top)				\
do {								\
  if (yydebug)							\
    yy_stack_print ((Bottom), (Top));				\
} while (YYID (0))


/*------------------------------------------------.
| Report that the YYRULE is going to be reduced.  |
`------------------------------------------------*/

#if (defined __STDC__ || defined __C99__FUNC__ \
     || defined __cplusplus || defined _MSC_VER)
static void
yy_reduce_print (YYSTYPE *yyvsp, int yyrule)
#else
static void
yy_reduce_print (yyvsp, yyrule)
    YYSTYPE *yyvsp;
    int yyrule;
#endif
{
  int yynrhs = yyr2[yyrule];
  int yyi;
  unsigned long int yylno = yyrline[yyrule];
  YYFPRINTF (stderr, "Reducing stack by rule %d (line %lu):\n",
	     yyrule - 1, yylno);
  /* The symbols being reduced.  */
  for (yyi = 0; yyi < yynrhs; yyi++)
    {
      YYFPRINTF (stderr, "   $%d = ", yyi + 1);
      yy_symbol_print (stderr, yyrhs[yyprhs[yyrule] + yyi],
		       &(yyvsp[(yyi + 1) - (yynrhs)])
		       		       );
      YYFPRINTF (stderr, "\n");
    }
}

# define YY_REDUCE_PRINT(Rule)		\
do {					\
  if (yydebug)				\
    yy_reduce_print (yyvsp, Rule); \
} while (YYID (0))

/* Nonzero means print parse trace.  It is left uninitialized so that
   multiple parsers can coexist.  */
int yydebug;
#else /* !YYDEBUG */
# define YYDPRINTF(Args)
# define YY_SYMBOL_PRINT(Title, Type, Value, Location)
# define YY_STACK_PRINT(Bottom, Top)
# define YY_REDUCE_PRINT(Rule)
#endif /* !YYDEBUG */


/* YYINITDEPTH -- initial size of the parser's stacks.  */
#ifndef	YYINITDEPTH
# define YYINITDEPTH 200
#endif

/* YYMAXDEPTH -- maximum size the stacks can grow to (effective only
   if the built-in stack extension method is used).

   Do not make this value too large; the results are undefined if
   YYSTACK_ALLOC_MAXIMUM < YYSTACK_BYTES (YYMAXDEPTH)
   evaluated with infinite-precision integer arithmetic.  */

#ifndef YYMAXDEPTH
# define YYMAXDEPTH 10000
#endif



#if YYERROR_VERBOSE

# ifndef yystrlen
#  if defined __GLIBC__ && defined _STRING_H
#   define yystrlen strlen
#  else
/* Return the length of YYSTR.  */
#if (defined __STDC__ || defined __C99__FUNC__ \
     || defined __cplusplus || defined _MSC_VER)
static YYSIZE_T
yystrlen (const char *yystr)
#else
static YYSIZE_T
yystrlen (yystr)
    const char *yystr;
#endif
{
  YYSIZE_T yylen;
  for (yylen = 0; yystr[yylen]; yylen++)
    continue;
  return yylen;
}
#  endif
# endif

# ifndef yystpcpy
#  if defined __GLIBC__ && defined _STRING_H && defined _GNU_SOURCE
#   define yystpcpy stpcpy
#  else
/* Copy YYSRC to YYDEST, returning the address of the terminating '\0' in
   YYDEST.  */
#if (defined __STDC__ || defined __C99__FUNC__ \
     || defined __cplusplus || defined _MSC_VER)
static char *
yystpcpy (char *yydest, const char *yysrc)
#else
static char *
yystpcpy (yydest, yysrc)
    char *yydest;
    const char *yysrc;
#endif
{
  char *yyd = yydest;
  const char *yys = yysrc;

  while ((*yyd++ = *yys++) != '\0')
    continue;

  return yyd - 1;
}
#  endif
# endif

# ifndef yytnamerr
/* Copy to YYRES the contents of YYSTR after stripping away unnecessary
   quotes and backslashes, so that it's suitable for yyerror.  The
   heuristic is that double-quoting is unnecessary unless the string
   contains an apostrophe, a comma, or backslash (other than
   backslash-backslash).  YYSTR is taken from yytname.  If YYRES is
   null, do not copy; instead, return the length of what the result
   would have been.  */
static YYSIZE_T
yytnamerr (char *yyres, const char *yystr)
{
  if (*yystr == '"')
    {
      YYSIZE_T yyn = 0;
      char const *yyp = yystr;

      for (;;)
	switch (*++yyp)
	  {
	  case '\'':
	  case ',':
	    goto do_not_strip_quotes;

	  case '\\':
	    if (*++yyp != '\\')
	      goto do_not_strip_quotes;
	    /* Fall through.  */
	  default:
	    if (yyres)
	      yyres[yyn] = *yyp;
	    yyn++;
	    break;

	  case '"':
	    if (yyres)
	      yyres[yyn] = '\0';
	    return yyn;
	  }
    do_not_strip_quotes: ;
    }

  if (! yyres)
    return yystrlen (yystr);

  return yystpcpy (yyres, yystr) - yyres;
}
# endif

/* Copy into YYRESULT an error message about the unexpected token
   YYCHAR while in state YYSTATE.  Return the number of bytes copied,
   including the terminating null byte.  If YYRESULT is null, do not
   copy anything; just return the number of bytes that would be
   copied.  As a special case, return 0 if an ordinary "syntax error"
   message will do.  Return YYSIZE_MAXIMUM if overflow occurs during
   size calculation.  */
static YYSIZE_T
yysyntax_error (char *yyresult, int yystate, int yychar)
{
  int yyn = yypact[yystate];

  if (! (YYPACT_NINF < yyn && yyn <= YYLAST))
    return 0;
  else
    {
      int yytype = YYTRANSLATE (yychar);
      YYSIZE_T yysize0 = yytnamerr (0, yytname[yytype]);
      YYSIZE_T yysize = yysize0;
      YYSIZE_T yysize1;
      int yysize_overflow = 0;
      enum { YYERROR_VERBOSE_ARGS_MAXIMUM = 5 };
      char const *yyarg[YYERROR_VERBOSE_ARGS_MAXIMUM];
      int yyx;

# if 0
      /* This is so xgettext sees the translatable formats that are
	 constructed on the fly.  */
      YY_("syntax error, unexpected %s");
      YY_("syntax error, unexpected %s, expecting %s");
      YY_("syntax error, unexpected %s, expecting %s or %s");
      YY_("syntax error, unexpected %s, expecting %s or %s or %s");
      YY_("syntax error, unexpected %s, expecting %s or %s or %s or %s");
# endif
      char *yyfmt;
      char const *yyf;
      static char const yyunexpected[] = "syntax error, unexpected %s";
      static char const yyexpecting[] = ", expecting %s";
      static char const yyor[] = " or %s";
      char yyformat[sizeof yyunexpected
		    + sizeof yyexpecting - 1
		    + ((YYERROR_VERBOSE_ARGS_MAXIMUM - 2)
		       * (sizeof yyor - 1))];
      char const *yyprefix = yyexpecting;

      /* Start YYX at -YYN if negative to avoid negative indexes in
	 YYCHECK.  */
      int yyxbegin = yyn < 0 ? -yyn : 0;

      /* Stay within bounds of both yycheck and yytname.  */
      int yychecklim = YYLAST - yyn + 1;
      int yyxend = yychecklim < YYNTOKENS ? yychecklim : YYNTOKENS;
      int yycount = 1;

      yyarg[0] = yytname[yytype];
      yyfmt = yystpcpy (yyformat, yyunexpected);

      for (yyx = yyxbegin; yyx < yyxend; ++yyx)
	if (yycheck[yyx + yyn] == yyx && yyx != YYTERROR)
	  {
	    if (yycount == YYERROR_VERBOSE_ARGS_MAXIMUM)
	      {
		yycount = 1;
		yysize = yysize0;
		yyformat[sizeof yyunexpected - 1] = '\0';
		break;
	      }
	    yyarg[yycount++] = yytname[yyx];
	    yysize1 = yysize + yytnamerr (0, yytname[yyx]);
	    yysize_overflow |= (yysize1 < yysize);
	    yysize = yysize1;
	    yyfmt = yystpcpy (yyfmt, yyprefix);
	    yyprefix = yyor;
	  }

      yyf = YY_(yyformat);
      yysize1 = yysize + yystrlen (yyf);
      yysize_overflow |= (yysize1 < yysize);
      yysize = yysize1;

      if (yysize_overflow)
	return YYSIZE_MAXIMUM;

      if (yyresult)
	{
	  /* Avoid sprintf, as that infringes on the user's name space.
	     Don't have undefined behavior even if the translation
	     produced a string with the wrong number of "%s"s.  */
	  char *yyp = yyresult;
	  int yyi = 0;
	  while ((*yyp = *yyf) != '\0')
	    {
	      if (*yyp == '%' && yyf[1] == 's' && yyi < yycount)
		{
		  yyp += yytnamerr (yyp, yyarg[yyi++]);
		  yyf += 2;
		}
	      else
		{
		  yyp++;
		  yyf++;
		}
	    }
	}
      return yysize;
    }
}
#endif /* YYERROR_VERBOSE */


/*-----------------------------------------------.
| Release the memory associated to this symbol.  |
`-----------------------------------------------*/

/*ARGSUSED*/
#if (defined __STDC__ || defined __C99__FUNC__ \
     || defined __cplusplus || defined _MSC_VER)
static void
yydestruct (const char *yymsg, int yytype, YYSTYPE *yyvaluep)
#else
static void
yydestruct (yymsg, yytype, yyvaluep)
    const char *yymsg;
    int yytype;
    YYSTYPE *yyvaluep;
#endif
{
  YYUSE (yyvaluep);

  if (!yymsg)
    yymsg = "Deleting";
  YY_SYMBOL_PRINT (yymsg, yytype, yyvaluep, yylocationp);

  switch (yytype)
    {

      default:
	break;
    }
}

/* Prevent warnings from -Wmissing-prototypes.  */
#ifdef YYPARSE_PARAM
#if defined __STDC__ || defined __cplusplus
int yyparse (void *YYPARSE_PARAM);
#else
int yyparse ();
#endif
#else /* ! YYPARSE_PARAM */
#if defined __STDC__ || defined __cplusplus
int yyparse (void);
#else
int yyparse ();
#endif
#endif /* ! YYPARSE_PARAM */


/* The lookahead symbol.  */
int yychar;

/* The semantic value of the lookahead symbol.  */
YYSTYPE yylval;

/* Number of syntax errors so far.  */
int yynerrs;



/*-------------------------.
| yyparse or yypush_parse.  |
`-------------------------*/

#ifdef YYPARSE_PARAM
#if (defined __STDC__ || defined __C99__FUNC__ \
     || defined __cplusplus || defined _MSC_VER)
int
yyparse (void *YYPARSE_PARAM)
#else
int
yyparse (YYPARSE_PARAM)
    void *YYPARSE_PARAM;
#endif
#else /* ! YYPARSE_PARAM */
#if (defined __STDC__ || defined __C99__FUNC__ \
     || defined __cplusplus || defined _MSC_VER)
int
yyparse (void)
#else
int
yyparse ()

#endif
#endif
{


    int yystate;
    /* Number of tokens to shift before error messages enabled.  */
    int yyerrstatus;

    /* The stacks and their tools:
       `yyss': related to states.
       `yyvs': related to semantic values.

       Refer to the stacks thru separate pointers, to allow yyoverflow
       to reallocate them elsewhere.  */

    /* The state stack.  */
    yytype_int16 yyssa[YYINITDEPTH];
    yytype_int16 *yyss;
    yytype_int16 *yyssp;

    /* The semantic value stack.  */
    YYSTYPE yyvsa[YYINITDEPTH];
    YYSTYPE *yyvs;
    YYSTYPE *yyvsp;

    YYSIZE_T yystacksize;

  int yyn;
  int yyresult;
  /* Lookahead token as an internal (translated) token number.  */
  int yytoken;
  /* The variables used to return semantic value and location from the
     action routines.  */
  YYSTYPE yyval;

#if YYERROR_VERBOSE
  /* Buffer for error messages, and its allocated size.  */
  char yymsgbuf[128];
  char *yymsg = yymsgbuf;
  YYSIZE_T yymsg_alloc = sizeof yymsgbuf;
#endif

#define YYPOPSTACK(N)   (yyvsp -= (N), yyssp -= (N))

  /* The number of symbols on the RHS of the reduced rule.
     Keep to zero when no symbol should be popped.  */
  int yylen = 0;

  yytoken = 0;
  yyss = yyssa;
  yyvs = yyvsa;
  yystacksize = YYINITDEPTH;

  YYDPRINTF ((stderr, "Starting parse\n"));

  yystate = 0;
  yyerrstatus = 0;
  yynerrs = 0;
  yychar = YYEMPTY; /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */
  yyssp = yyss;
  yyvsp = yyvs;

  goto yysetstate;

/*------------------------------------------------------------.
| yynewstate -- Push a new state, which is found in yystate.  |
`------------------------------------------------------------*/
 yynewstate:
  /* In all cases, when you get here, the value and location stacks
     have just been pushed.  So pushing a state here evens the stacks.  */
  yyssp++;

 yysetstate:
  *yyssp = yystate;

  if (yyss + yystacksize - 1 <= yyssp)
    {
      /* Get the current used size of the three stacks, in elements.  */
      YYSIZE_T yysize = yyssp - yyss + 1;

#ifdef yyoverflow
      {
	/* Give user a chance to reallocate the stack.  Use copies of
	   these so that the &'s don't force the real ones into
	   memory.  */
	YYSTYPE *yyvs1 = yyvs;
	yytype_int16 *yyss1 = yyss;

	/* Each stack pointer address is followed by the size of the
	   data in use in that stack, in bytes.  This used to be a
	   conditional around just the two extra args, but that might
	   be undefined if yyoverflow is a macro.  */
	yyoverflow (YY_("memory exhausted"),
		    &yyss1, yysize * sizeof (*yyssp),
		    &yyvs1, yysize * sizeof (*yyvsp),
		    &yystacksize);

	yyss = yyss1;
	yyvs = yyvs1;
      }
#else /* no yyoverflow */
# ifndef YYSTACK_RELOCATE
      goto yyexhaustedlab;
# else
      /* Extend the stack our own way.  */
      if (YYMAXDEPTH <= yystacksize)
	goto yyexhaustedlab;
      yystacksize *= 2;
      if (YYMAXDEPTH < yystacksize)
	yystacksize = YYMAXDEPTH;

      {
	yytype_int16 *yyss1 = yyss;
	union yyalloc *yyptr =
	  (union yyalloc *) YYSTACK_ALLOC (YYSTACK_BYTES (yystacksize));
	if (! yyptr)
	  goto yyexhaustedlab;
	YYSTACK_RELOCATE (yyss_alloc, yyss);
	YYSTACK_RELOCATE (yyvs_alloc, yyvs);
#  undef YYSTACK_RELOCATE
	if (yyss1 != yyssa)
	  YYSTACK_FREE (yyss1);
      }
# endif
#endif /* no yyoverflow */

      yyssp = yyss + yysize - 1;
      yyvsp = yyvs + yysize - 1;

      YYDPRINTF ((stderr, "Stack size increased to %lu\n",
		  (unsigned long int) yystacksize));

      if (yyss + yystacksize - 1 <= yyssp)
	YYABORT;
    }

  YYDPRINTF ((stderr, "Entering state %d\n", yystate));

  if (yystate == YYFINAL)
    YYACCEPT;

  goto yybackup;

/*-----------.
| yybackup.  |
`-----------*/
yybackup:

  /* Do appropriate processing given the current state.  Read a
     lookahead token if we need one and don't already have one.  */

  /* First try to decide what to do without reference to lookahead token.  */
  yyn = yypact[yystate];
  if (yyn == YYPACT_NINF)
    goto yydefault;

  /* Not known => get a lookahead token if don't already have one.  */

  /* YYCHAR is either YYEMPTY or YYEOF or a valid lookahead symbol.  */
  if (yychar == YYEMPTY)
    {
      YYDPRINTF ((stderr, "Reading a token: "));
      yychar = YYLEX;
    }

  if (yychar <= YYEOF)
    {
      yychar = yytoken = YYEOF;
      YYDPRINTF ((stderr, "Now at end of input.\n"));
    }
  else
    {
      yytoken = YYTRANSLATE (yychar);
      YY_SYMBOL_PRINT ("Next token is", yytoken, &yylval, &yylloc);
    }

  /* If the proper action on seeing token YYTOKEN is to reduce or to
     detect an error, take that action.  */
  yyn += yytoken;
  if (yyn < 0 || YYLAST < yyn || yycheck[yyn] != yytoken)
    goto yydefault;
  yyn = yytable[yyn];
  if (yyn <= 0)
    {
      if (yyn == 0 || yyn == YYTABLE_NINF)
	goto yyerrlab;
      yyn = -yyn;
      goto yyreduce;
    }

  /* Count tokens shifted since error; after three, turn off error
     status.  */
  if (yyerrstatus)
    yyerrstatus--;

  /* Shift the lookahead token.  */
  YY_SYMBOL_PRINT ("Shifting", yytoken, &yylval, &yylloc);

  /* Discard the shifted token.  */
  yychar = YYEMPTY;

  yystate = yyn;
  *++yyvsp = yylval;

  goto yynewstate;


/*-----------------------------------------------------------.
| yydefault -- do the default action for the current state.  |
`-----------------------------------------------------------*/
yydefault:
  yyn = yydefact[yystate];
  if (yyn == 0)
    goto yyerrlab;
  goto yyreduce;


/*-----------------------------.
| yyreduce -- Do a reduction.  |
`-----------------------------*/
yyreduce:
  /* yyn is the number of a rule to reduce with.  */
  yylen = yyr2[yyn];

  /* If YYLEN is nonzero, implement the default value of the action:
     `$$ = $1'.

     Otherwise, the following line sets YYVAL to garbage.
     This behavior is undocumented and Bison
     users should not rely upon it.  Assigning to YYVAL
     unconditionally makes the parser a bit smaller, and it avoids a
     GCC warning that YYVAL may be used uninitialized.  */
  yyval = yyvsp[1-yylen];


  YY_REDUCE_PRINT (yyn);
  switch (yyn)
    {
      

/* Line 1455 of yacc.c  */
#line 1768 "parser.cpp"
      default: break;
    }
  YY_SYMBOL_PRINT ("-> $$ =", yyr1[yyn], &yyval, &yyloc);

  YYPOPSTACK (yylen);
  yylen = 0;
  YY_STACK_PRINT (yyss, yyssp);

  *++yyvsp = yyval;

  /* Now `shift' the result of the reduction.  Determine what state
     that goes to, based on the state we popped back to and the rule
     number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTOKENS] + *yyssp;
  if (0 <= yystate && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTOKENS];

  goto yynewstate;


/*------------------------------------.
| yyerrlab -- here on detecting error |
`------------------------------------*/
yyerrlab:
  /* If not already recovering from an error, report this error.  */
  if (!yyerrstatus)
    {
      ++yynerrs;
#if ! YYERROR_VERBOSE
      yyerror (YY_("syntax error"));
#else
      {
	YYSIZE_T yysize = yysyntax_error (0, yystate, yychar);
	if (yymsg_alloc < yysize && yymsg_alloc < YYSTACK_ALLOC_MAXIMUM)
	  {
	    YYSIZE_T yyalloc = 2 * yysize;
	    if (! (yysize <= yyalloc && yyalloc <= YYSTACK_ALLOC_MAXIMUM))
	      yyalloc = YYSTACK_ALLOC_MAXIMUM;
	    if (yymsg != yymsgbuf)
	      YYSTACK_FREE (yymsg);
	    yymsg = (char *) YYSTACK_ALLOC (yyalloc);
	    if (yymsg)
	      yymsg_alloc = yyalloc;
	    else
	      {
		yymsg = yymsgbuf;
		yymsg_alloc = sizeof yymsgbuf;
	      }
	  }

	if (0 < yysize && yysize <= yymsg_alloc)
	  {
	    (void) yysyntax_error (yymsg, yystate, yychar);
	    yyerror (yymsg);
	  }
	else
	  {
	    yyerror (YY_("syntax error"));
	    if (yysize != 0)
	      goto yyexhaustedlab;
	  }
      }
#endif
    }



  if (yyerrstatus == 3)
    {
      /* If just tried and failed to reuse lookahead token after an
	 error, discard it.  */

      if (yychar <= YYEOF)
	{
	  /* Return failure if at end of input.  */
	  if (yychar == YYEOF)
	    YYABORT;
	}
      else
	{
	  yydestruct ("Error: discarding",
		      yytoken, &yylval);
	  yychar = YYEMPTY;
	}
    }

  /* Else will try to reuse lookahead token after shifting the error
     token.  */
  goto yyerrlab1;


/*---------------------------------------------------.
| yyerrorlab -- error raised explicitly by YYERROR.  |
`---------------------------------------------------*/
yyerrorlab:

  /* Pacify compilers like GCC when the user code never invokes
     YYERROR and the label yyerrorlab therefore never appears in user
     code.  */
  if (/*CONSTCOND*/ 0)
     goto yyerrorlab;

  /* Do not reclaim the symbols of the rule which action triggered
     this YYERROR.  */
  YYPOPSTACK (yylen);
  yylen = 0;
  YY_STACK_PRINT (yyss, yyssp);
  yystate = *yyssp;
  goto yyerrlab1;


/*-------------------------------------------------------------.
| yyerrlab1 -- common code for both syntax error and YYERROR.  |
`-------------------------------------------------------------*/
yyerrlab1:
  yyerrstatus = 3;	/* Each real token shifted decrements this.  */

  for (;;)
    {
      yyn = yypact[yystate];
      if (yyn != YYPACT_NINF)
	{
	  yyn += YYTERROR;
	  if (0 <= yyn && yyn <= YYLAST && yycheck[yyn] == YYTERROR)
	    {
	      yyn = yytable[yyn];
	      if (0 < yyn)
		break;
	    }
	}

      /* Pop the current state because it cannot handle the error token.  */
      if (yyssp == yyss)
	YYABORT;


      yydestruct ("Error: popping",
		  yystos[yystate], yyvsp);
      YYPOPSTACK (1);
      yystate = *yyssp;
      YY_STACK_PRINT (yyss, yyssp);
    }

  *++yyvsp = yylval;


  /* Shift the error token.  */
  YY_SYMBOL_PRINT ("Shifting", yystos[yyn], yyvsp, yylsp);

  yystate = yyn;
  goto yynewstate;


/*-------------------------------------.
| yyacceptlab -- YYACCEPT comes here.  |
`-------------------------------------*/
yyacceptlab:
  yyresult = 0;
  goto yyreturn;

/*-----------------------------------.
| yyabortlab -- YYABORT comes here.  |
`-----------------------------------*/
yyabortlab:
  yyresult = 1;
  goto yyreturn;

#if !defined(yyoverflow) || YYERROR_VERBOSE
/*-------------------------------------------------.
| yyexhaustedlab -- memory exhaustion comes here.  |
`-------------------------------------------------*/
yyexhaustedlab:
  yyerror (YY_("memory exhausted"));
  yyresult = 2;
  /* Fall through.  */
#endif

yyreturn:
  if (yychar != YYEMPTY)
     yydestruct ("Cleanup: discarding lookahead",
		 yytoken, &yylval);
  /* Do not reclaim the symbols of the rule which action triggered
     this YYABORT or YYACCEPT.  */
  YYPOPSTACK (yylen);
  YY_STACK_PRINT (yyss, yyssp);
  while (yyssp != yyss)
    {
      yydestruct ("Cleanup: popping",
		  yystos[*yyssp], yyvsp);
      YYPOPSTACK (1);
    }
#ifndef yyoverflow
  if (yyss != yyssa)
    YYSTACK_FREE (yyss);
#endif
#if YYERROR_VERBOSE
  if (yymsg != yymsgbuf)
    YYSTACK_FREE (yymsg);
#endif
  /* Make sure YYID is used.  */
  return YYID (yyresult);
}



